language: node_js
node_js:
  - "4"
  - "6"
  - "8"
  - "10"
matrix:
  fast_finish: true
script: "npm run-script test-ci"
after_script: "npm install coveralls@2.11.8 && cat ./coverage/lcov.info | coveralls"
