language: node_js
node_js:
  - "0.12.7"
  - "4"
  - "6"
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "6" 
script: "npm run-script test-ci"
after_script: "npm install coveralls@2.11.8 && cat ./coverage/lcov.info | coveralls"
